<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\RIoT2.Elsa.Studio\RIoT2.Elsa.Studio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elsa" Version="3.7.1" />
    <PackageReference Include="Elsa.Expressions.CSharp" Version="3.7.1" />
    <PackageReference Include="Elsa.Expressions.JavaScript" Version="3.7.1" />
    <PackageReference Include="Elsa.Expressions.Liquid" Version="3.7.1" />
    <PackageReference Include="Elsa.Http" Version="3.7.1" />
    <PackageReference Include="Elsa.Identity" Version="3.7.1" />
    <PackageReference Include="Elsa.Persistence.EFCore.Sqlite" Version="3.7.1" />
    <PackageReference Include="Elsa.Retention" Version="3.7.1" />
    <PackageReference Include="Elsa.Scheduling" Version="3.7.1" />
    <PackageReference Include="Elsa.Workflows.Api" Version="3.7.1" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="RIoT2.Core" Version="0.1.41" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="RIoT\Protos\riot.proto" GrpcServices="Server" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
